spring:
  application:
    name: lavava2026

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: none

api:
  valorant:
    base_url: ${VALORANT_API_URL:https://api.henrikdev.xyz}
    key: ${VALORANT_API_KEY:HDEV-5c791baf-4608-4d1a-a7cc-791488ad0013}
